
import type { Review, Category } from './types';
import imageData from './placeholder-images.json';

const findImage = (id: string) => imageData.placeholderImages.find(img => img.id === id)?.imageUrl || '';

export const categories: Category[] = [
  { name: 'Geladeira', slug: 'geladeira' },
  { name: 'Fogão', slug: 'fogao' },
  { name: 'Micro-ondas', slug: 'micro-ondas' },
  { name: 'Máquina de Lavar', slug: 'maquina-de-lavar' },
  { name: 'Air Fryer', slug: 'air-fryer' },
  { name: 'Cafeteira', slug: 'cafeteira' },
  { name: 'Liquidificador', slug: 'liquidificador' },
  { name: 'Televisão', slug: 'televisao' },
];

export const reviews: Review[] = [
  {
    id: '1',
    slug: 'geladeira-frost-free-brastemp-brx50',
    title: 'Geladeira Frost Free Brastemp BRX50',
    category: 'geladeira',
    rating: 4.8,
    image: findImage('refrigerator-1'),
    images: [findImage('refrigerator-1'), findImage('refrigerator-2'), findImage('refrigerator-3')],
    summary: 'Uma geladeira espaçosa e eficiente, ideal para famílias grandes que buscam tecnologia e design moderno.',
    pros: [
      'Grande capacidade interna',
      'Painel touch intuitivo',
      'Baixo consumo de energia',
      'Design moderno em inox',
    ],
    cons: [
      'Preço elevado',
      'Gavetas de plástico frágeis',
    ],
    content: `A Geladeira Frost Free Brastemp BRX50 é um dos modelos mais cobiçados do mercado, e não é para menos. Com um design arrojado em aço inox e um painel touch screen na porta, ela impressiona logo de cara. Em nossos testes, o sistema de refrigeração se mostrou extremamente eficiente, mantendo a temperatura estável em todos os compartimentos. O consumo de energia, classificado como A+++, é um grande atrativo, resultando em economia na conta de luz a longo prazo. Com 400 litros de capacidade, o espaço interno é generoso. As prateleiras de vidro são ajustáveis, permitindo uma organização flexível. O compartimento "Espaço Adapt" na porta é um diferencial, ideal para armazenar itens de diferentes tamanhos. No entanto, as gavetas de acrílico do freezer e da área de legumes pareceram um pouco frágeis para um produto dessa categoria. A Brastemp BRX50 é uma excelente escolha para quem não abre mão de capacidade, tecnologia e eficiência energética. Apesar do preço mais salgado e de alguns detalhes no acabamento interno, seus benefícios superam os pontos negativos, tornando-a um investimento que vale a pena para a cozinha moderna.`,
    technicalSpecs: {
      'Capacidade Total': '400L',
      'Tipo de Degelo': 'Frost Free',
      'Consumo': '35 kWh/mês',
      'Voltagem': '110V/220V (Não é Bivolt)',
      'Altura': '185 cm',
      'Largura': '62 cm',
      'Profundidade': '75 cm',
      'Peso': '71 kg'
    },
    publishedAt: '2024-07-20T10:00:00Z',
    scores: {
      'Capacidade': 9.5,
      'Eficiência Energética': 9.2,
      'Design': 9.0,
      'Custo-benefício': 8.0,
    },
  },
  {
    id: '2',
    slug: 'fogao-5-bocas-consul-cfp50',
    title: 'Fogão 5 Bocas Consul CFP50',
    category: 'fogao',
    rating: 4.5,
    image: findImage('stove-1'),
    images: [findImage('stove-1')],
    summary: 'Um fogão robusto e funcional que entrega ótimo desempenho com um excelente custo-benefício.',
    pros: [
      'Acendimento automático total',
      'Forno espaçoso com boa vedação',
      'Queimador rápido potente',
      'Fácil de limpar',
    ],
    cons: [
      'Design simples',
      'Grades da mesa poderiam ser mais robustas',
    ],
    content: `O Fogão 5 Bocas Consul CFP50 é a prova de que não é preciso gastar uma fortuna para ter um eletrodoméstico de qualidade na cozinha. Ele combina funcionalidades essenciais com um desempenho confiável. A mesa de inox conta com 5 queimadores, incluindo um queimador rápido que acelera o preparo de alimentos. O acendimento é automático tanto na mesa quanto no forno, o que é um ponto muito positivo. O forno de 96 litros é espaçoso e seu vidro duplo garante uma boa vedação, mantendo o calor e economizando gás. A limpeza é facilitada pelo revestimento esmaltado do forno e pela mesa de inox sem furações. As grades são individuais e leves, o que ajuda na hora de lavar, embora pudessem ser um pouco mais espessas para dar mais estabilidade às panelas. Para quem busca um fogão 5 bocas eficiente, prático e com preço justo, o Consul CFP50 é uma das melhores opções do mercado. Ele não tem grandes inovações tecnológicas, mas cumpre com maestria o seu papel principal.`,
    technicalSpecs: {
      'Número de Bocas': '5',
      'Tipo de Acendimento': 'Automático',
      'Capacidade do Forno': '96L',
      'Voltagem': 'Bivolt',
      'Material da mesa': 'Aço Inox',
      'Altura': '96 cm',
      'Largura': '76 cm',
      'Profundidade': '63 cm',
      'Peso': '38 kg',
    },
    scores: {
        'Custo-benefício': 9.5,
        'Desempenho': 9.0,
        'Capacidade do Forno': 9.5,
        'Facilidade de Limpeza': 9.0
    },
    offers: [
        { id: '1', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 1299.00, offerUrl: '#' },
        { id: '2', store: 'Ponto', storeLogoUrl: '/images/stores/ponto.svg', price: 1329.00, offerUrl: '#' },
        { id: '3', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 1359.00, offerUrl: '#' }
    ],
    publishedAt: '2024-07-18T14:30:00Z',
  },
    {
    id: '3',
    slug: 'micro-ondas-electrolux-mef41-31l',
    title: 'Micro-ondas Electrolux 31L MEF41 Branco',
    category: 'micro-ondas',
    rating: 4.7,
    image: findImage('microwave-1'),
    images: [findImage('microwave-1')],
    imageAspectRatio: 'video',
    summary: 'Praticidade e funções inteligentes para o dia a dia.',
    content: `O Micro-ondas Electrolux 31L MEF41 oferece ótimo espaço interno e funções automáticas que facilitam o preparo de pratos do cotidiano. Seu painel é intuitivo, com teclas de atalho para receitas rápidas, como pipoca, arroz e lasanha. Além disso, o acabamento moderno combina com qualquer cozinha e é fácil de limpar. O destaque vai para a função “Manter Aquecido”, que conserva a temperatura dos alimentos por mais tempo sem ressecar. Ideal para famílias pequenas e médias.`,
    technicalSpecs: {
      'Capacidade': '31 Litros',
      'Potência': '1500W',
      'Voltagem': '110V ou 220V',
      'Painel': 'Digital',
      'Cor': 'Branco',
      'Funções Pré-programadas': 'Sim',
      'Função Descongelar': 'Sim',
      'Trava de Segurança': 'Sim',
      'Eficiência Energética': 'Classe A',
      'Garantia': '12 meses'
    },
    scores: {
      'Custo-benefício': 9.0,
      'Desempenho': 9.5,
      'Capacidade': 9.0,
      'Facilidade de Uso': 9.5,
    },
    offers: [
      { id: '1', store: 'Ponto', storeLogoUrl: '/images/stores/ponto.svg', price: 749.00, offerUrl: '#' },
      { id: '2', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 729.00, offerUrl: '#' },
      { id: '3', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 739.00, offerUrl: '#' }
    ],
    publishedAt: '2024-07-15T09:00:00Z',
  },
  {
    id: '4',
    slug: 'maquina-de-lavar-samsung-ecobubble-11kg',
    title: 'Máquina de Lavar Samsung EcoBubble 11kg',
    category: 'maquina-de-lavar',
    rating: 4.9,
    image: findImage('washing-machine-1'),
    images: [findImage('washing-machine-1')],
    imageAspectRatio: 'portrait',
    summary: 'Tecnologia de ponta para uma lavagem mais eficiente e econômica. A EcoBubble 11kg da Samsung impressiona.',
    pros: [
      'Tecnologia EcoBubble economiza energia',
      'Motor Digital Inverter silencioso e durável (10 anos de garantia)',
      'Ciclo de lavagem a vapor (Steam)',
      'Design elegante',
    ],
    cons: [
      'Preço acima da média',
      'Interface pode ser complexa para alguns usuários',
    ],
    content: `A Samsung EcoBubble WF11A é uma lavadora front-load que redefine o conceito de lavar roupas. Sua principal tecnologia, a EcoBubble, dissolve o sabão com ar e água antes do ciclo começar, criando bolhas que penetram no tecido mais rápido, permitindo uma lavagem eficaz mesmo com água fria. A qualidade da lavagem é impecável. Roupas saem limpas e bem cuidadas. O ciclo a vapor é excelente para higienizar e reduzir amassados. O motor Digital Inverter é extremamente silencioso, permitindo lavar roupas a qualquer hora do dia sem incômodos. O design é moderno e o painel digital é completo. Para quem gosta de tecnologia, é um prato cheio, mas a quantidade de opções pode confundir usuários menos experientes no início. A capacidade de 11kg atende bem famílias de até 4 pessoas. A Samsung EcoBubble 11kg é um investimento alto, mas que se paga com o tempo em economia de água, energia e na qualidade da lavagem que preserva suas roupas. É, sem dúvidas, uma das melhores máquinas de lavar do mercado.`,
    technicalSpecs: {
      'Capacidade de Lavagem': '11kg',
      'Tipo': 'Front-load (Abertura frontal)',
      'Motor': 'Digital Inverter',
      'Programas de Lavagem': '22',
      'Velocidade de Centrifugação': '1400 RPM',
      'Voltagem': '110V/220V (Não é Bivolt)',
      'Altura': '85 cm',
      'Largura': '60 cm',
      'Profundidade': '65 cm',
      'Peso': '67 kg'
    },
    scores: {
      'Eficiência de Lavagem': 9.8,
      'Economia de Energia/Água': 9.5,
      'Nível de Ruído': 9.7,
      'Custo-benefício': 8.5,
    },
    publishedAt: '2024-07-12T11:00:00Z',
  },
    {
    id: '5',
    slug: 'air-fryer-mondial-family-iv-af-30',
    title: 'Air Fryer Mondial Family IV AF-30 3,5L Preta',
    category: 'air-fryer',
    rating: 4.6,
    image: findImage('air-fryer-1'),
    images: [findImage('air-fryer-1')],
    summary: 'Crocância e praticidade com ótimo custo-benefício.',
    content: `A Air Fryer Mondial 3,5L é uma das mais vendidas do Brasil por unir preço acessível e ótimo desempenho. Ela prepara alimentos crocantes com pouco ou nenhum óleo, sendo ideal para refeições rápidas e saudáveis. Seu cesto antiaderente facilita a limpeza, e o controle de temperatura vai de 80ºC a 200ºC. O design compacto é ideal para cozinhas pequenas, e o consumo de energia é baixo, mesmo com uso diário.`,
    technicalSpecs: {
      'Capacidade': '3,5 Litros',
      'Potência': '1500W',
      'Voltagem': '110V ou 220V',
      'Controle de Temperatura': '80ºC a 200ºC',
      'Timer': '60 minutos',
      'Cesto': 'Antiaderente removível',
      'Cor': 'Preta',
      'Consumo': '1,5 kWh',
      'Garantia': '12 meses'
    },
    scores: {
      'Custo-benefício': 9.5,
      'Desempenho': 9.0,
      'Capacidade': 8.5,
      'Praticidade': 9.0
    },
    offers: [
      { id: '1', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 359.00, offerUrl: '#' },
      { id: '2', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 369.00, offerUrl: '#' },
      { id: '3', store: 'Ponto', storeLogoUrl: '/images/stores/ponto.svg', price: 355.00, offerUrl: '#' }
    ],
    publishedAt: '2024-07-10T16:00:00Z',
  },
  {
    id: '6',
    slug: 'liquidificador-oster-ostc-800',
    title: 'Liquidificador Oster Clássico',
    category: 'liquidificador',
    rating: 4.7,
    image: findImage('blender-1'),
    images: [findImage('blender-1')],
    imageAspectRatio: 'portrait',
    summary: 'Um ícone da durabilidade, o liquidificador Oster Clássico une design retrô, jarra de vidro e um motor potente.',
    pros: [
      'Jarra de vidro resistente que não pega cheiro',
      'Motor de 600W potente',
      'Sistema de encaixe metal com metal (All-Metal Drive)',
      'Design retrô icônico',
    ],
    cons: [
      'Jarra de vidro é pesada',
      'Apenas 3 velocidades',
      'Tampa pouco prática',
    ],
    content: `O liquidificador Osterizer Clássico é um daqueles produtos que atravessam gerações. Famoso por sua robustez, ele continua sendo uma escolha popular. O grande diferencial é o sistema All-Metal Drive, onde as peças de encaixe do motor e da jarra são de metal, garantindo uma durabilidade muito acima da média. A jarra de vidro de 1,25L é outro ponto forte: não risca, não mancha e não retém odores, além de ser mais higiênica. O contraponto é seu peso, que exige cuidado no manuseio. O motor de 600W, combinado com a lâmina de 4 facas em aço inox, tritura gelo, polpas congeladas e outros ingredientes duros com facilidade. O controle é simples, com uma alavanca para 3 velocidades. Embora funcional, mais opções de velocidade poderiam ser úteis. O Oster Clássico é para quem valoriza durabilidade acima de tudo. Ele pode não ter as dezenas de funções dos modelos modernos, mas sua construção sólida e motor potente garantem que ele será um companheiro na cozinha por muitos e muitos anos.`,
    technicalSpecs: {
      'Potência': '600W',
      'Capacidade da Jarra': '1.25L',
      'Material da Jarra': 'Vidro',
      'Velocidades': '3',
      'Voltagem': '110V/220V (Não é Bivolt)',
      'Altura': '40.5 cm',
      'Largura': '19.5 cm',
      'Profundidade': '19.5 cm',
      'Peso': '3.6 kg'
    },
    scores: {
      'Durabilidade': 9.9,
      'Potência': 9.0,
      'Design': 8.8,
      'Custo-benefício': 8.5,
    },
    publishedAt: '2024-07-08T13:20:00Z',
  },
  {
    id: '7',
    slug: 'geladeira-consul-cycle-defrost-crd37eb',
    title: 'Geladeira Consul Cycle Defrost Duplex 334 Litros',
    category: 'geladeira',
    rating: 4.4,
    image: findImage('refrigerator-2'),
    images: [findImage('refrigerator-2'), findImage('refrigerator-1'), findImage('refrigerator-3')],
    imageAspectRatio: 'portrait',
    summary: 'Uma geladeira prática e econômica, ideal para quem precisa de um bom espaço no freezer e quer um modelo mais simples de manter.',
    content: `A Geladeira Consul CRD37EB Cycle Defrost Duplex é um eletrodoméstico funcional e econômico, ideal para cozinhas que buscam eficiência com o mínimo de manutenção. Com 334 litros de capacidade total, ela se destaca pela praticidade do sistema Cycle Defrost, que elimina a necessidade de descongelamento frequente, bastando fazê-lo apenas duas vezes por ano. O compartimento do freezer, com 76 litros, é considerado de Supercapacidade e oferece espaço suficiente para congelar uma grande quantidade de alimentos, incluindo o compartimento especial "Gelo Extra". Na parte da geladeira (258 litros), o grande diferencial é a flexibilidade: as prateleiras internas podem ser ajustadas em 15 níveis de altura diferentes, permitindo que você reorganize o espaço para itens de todos os tamanhos, como panelas grandes ou garrafas altas. O Gavetão Hortifrúti ajuda a manter frutas e legumes frescos e organizados. A classificação Classe A garante que o consumo de energia seja um dos mais baixos da categoria.`,
    technicalSpecs: {
      'Tecnologia de Degelo': 'Cycle Defrost',
      'Capacidade Total': '334 Litros',
      'Capacidade do Refrigerador': '258 Litros',
      'Capacidade do Freezer': '76 Litros',
      'Eficiência Energética': 'Classe A',
      'Consumo Médio': '43,5kWh/mês',
      'Voltagem': '110V ou 220V (Não é Bivolt)',
      'Altura': '166.9 cm',
      'Largura': '60.3 cm',
      'Profundidade': '63.4 cm',
      'Peso': '58 kg'
    },
    scores: {
        'Custo-benefício': 9,
        'Desempenho (Eficiência)': 9.5,
        'Capacidade de Refrigeração': 9,
        'Espaço do Freezer': 9,
    },
    priceRange: 'R$ 1.900 a R$ 2.500',
    publishedAt: '2024-07-28T11:00:00Z',
    offers: [
      { id: '1', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 2199.90, offerUrl: '#' },
      { id: '2', store: 'Mercado Livre', storeLogoUrl: '/images/stores/mercado-livre.svg', price: 2249.00, offerUrl: '#' },
      { id: '3', store: 'Magazine Luiza', storeLogoUrl: '/images/stores/magalu.svg', price: 2159.99, offerUrl: '#' },
    ],
  },
  {
    id: '9',
    slug: 'cafeteira-nespresso-essenza-mini',
    title: 'Cafeteira Nespresso Essenza Mini',
    category: 'cafeteira',
    rating: 4.7,
    image: findImage('coffee-maker-1'),
    images: [findImage('coffee-maker-1')],
    imageAspectRatio: 'video',
    summary: 'Compacta, moderna e ideal para quem ama café expresso.',
    content: `A Nespresso Essenza Mini é uma cafeteira compacta e prática, perfeita para quem busca espresso de qualidade com rapidez. Com design elegante, ela prepara cafés curtos e longos com apenas um toque. O aquecimento é rápido, e o sistema de cápsulas garante sempre o mesmo sabor e aroma. Ideal para uso doméstico ou no escritório, oferece ótimo custo-benefício e facilidade de limpeza.`,
    technicalSpecs: {
      'Tipo': 'Espresso com cápsulas',
      'Reservatório de Água': '600 ml',
      'Pressão': '19 bar',
      'Tempo de Aquecimento': '25 segundos',
      'Cores': 'Preto ou Vermelho',
      'Voltagem': '110V ou 220V',
      'Eficiência Energética': 'Classe A',
      'Consumo': '0,8 kWh',
      'Garantia': '12 meses'
    },
    scores: {
      'Custo-benefício': 9.0,
      'Desempenho': 9.5,
      'Design': 9.5,
      'Praticidade': 9.0
    },
    offers: [
      { id: '1', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 549.00, offerUrl: '#' },
      { id: '2', store: 'Americanas', storeLogoUrl: '/images/stores/americanas.svg', price: 559.00, offerUrl: '#' },
      { id: '3', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 569.00, offerUrl: '#' }
    ],
    publishedAt: '2024-07-30T15:00:00Z',
  },
  {
    id: '10',
    slug: 'smart-tv-samsung-crystal-4k-55',
    title: 'Smart TV Samsung Crystal UHD 4K 55"',
    category: 'televisao',
    rating: 4.7,
    image: findImage('television-1'),
    images: [findImage('television-1')],
    imageAspectRatio: 'video',
    summary: 'Uma TV 4K com cores vibrantes, design fino e um sistema operacional rápido e intuitivo.',
    content: `A Smart TV Samsung Crystal UHD 4K de 55 polegadas é um dos modelos de entrada no universo 4K da marca, mas que entrega uma experiência surpreendente. O painel com tecnologia Crystal Display oferece cores mais puras e vibrantes. O processador Crystal 4K faz um ótimo trabalho de upscaling de conteúdos de menor resolução. O suporte a HDR aumenta o contraste e o brilho, proporcionando cenas mais realistas. O som é decente para o uso diário, mas para uma experiência de cinema em casa, uma soundbar é recomendada. O sistema operacional Tizen é rápido e fácil de navegar, com os principais aplicativos de streaming já instalados. A TV conta com 3 entradas HDMI, 1 USB e conectividade Wi-Fi e Bluetooth. O controle remoto único é minimalista e simplifica o controle de outros aparelhos conectados. Para quem busca uma excelente porta de entrada para o mundo 4K, a Samsung Crystal UHD 4K é uma escolha difícil de bater. Ela oferece uma qualidade de imagem impressionante, um sistema smart completo e um design elegante por um preço competitivo.`,
    technicalSpecs: {
      'Tamanho da Tela': '55 polegadas',
      'Resolução': '4K (3840 x 2160)',
      'Processador': 'Crystal 4K',
      'Sistema Operacional': 'Tizen',
      'Conexões': '3 HDMI, 1 USB, Wi-Fi, Bluetooth',
      'Voltagem': 'Bivolt',
      'Altura': '70.7 cm',
      'Largura': '123 cm',
      'Profundidade': '6 cm',
      'Peso': '13.9 kg'
    },
    scores: {
      'Qualidade de Imagem': 9.2,
      'Recursos Smart': 9.0,
      'Design': 9.5,
      'Custo-benefício': 9.3,
    },
    publishedAt: '2024-08-01T12:00:00Z',
  },
  {
    id: '11',
    slug: 'fogao-atlas-4-bocas-agile-glass',
    title: 'Fogão Atlas 4 Bocas Agile Glass Preto com Mesa de Vidro',
    category: 'fogao',
    rating: 4.6,
    image: findImage('stove-2'),
    images: [findImage('stove-2')],
    summary: 'Uma opção moderna e eficiente, ideal para cozinhas pequenas e quem busca custo-benefício.',
    content: `O Fogão Atlas 4 Bocas Agile Glass é uma excelente escolha para quem procura um modelo prático, com bom desempenho e design moderno. Seu grande destaque é a mesa de vidro temperado, que facilita a limpeza e dá um toque elegante à cozinha. Os queimadores possuem diferentes potências, garantindo agilidade no preparo dos alimentos. O forno é espaçoso para a categoria, com visor amplo e luz interna, permitindo acompanhar o cozimento com facilidade. Além disso, o acendimento automático e os botões removíveis tornam o uso mais prático e seguro no dia a dia.`,
    technicalSpecs: {
      'Tipo': 'Fogão de Piso',
      'Queimadores': '4',
      'Acendimento': 'Automático',
      'Mesa': 'Vidro Temperado',
      'Forno': '50 Litros',
      'Luz Interna': 'Sim',
      'Cor': 'Preto',
      'Consumo': '0,1 kg/h (GLP)',
      'Tipo de Gás': 'GLP (Conversível para GN)',
      'Eficiência Energética': 'Classe A',
      'Garantia': '12 meses',
      'Altura': '87.9 cm',
      'Largura': '48 cm',
      'Profundidade': '59.5 cm',
      'Peso': '24.9 kg'
    },
    scores: {
        'Custo-benefício': 9.0,
        'Desempenho': 9.0,
        'Capacidade do Forno': 8.5,
        'Design': 9.5
    },
    publishedAt: '2024-07-29T09:00:00Z',
    offers: [
        { id: '1', store: 'Magazine Luiza', storeLogoUrl: '/images/stores/magalu.svg', price: 999.00, offerUrl: '#' },
        { id: '2', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 1049.00, offerUrl: '#' }
    ]
  },
  {
    id: '12',
    slug: 'fogao-electrolux-5-bocas-76exv',
    title: 'Fogão 5 Bocas Electrolux com Mesa de Vidro 76EXV',
    category: 'fogao',
    rating: 4.8,
    image: findImage('stove-3'),
    summary: 'Design premium com mesa de vidro, queimador tripla-chama e forno de alta capacidade para quem leva a cozinha a sério.',
    content: `O Fogão 5 Bocas Electrolux 76EXV é um modelo que combina performance e um visual sofisticado, ideal para cozinhas modernas. A mesa de vidro temperado, além de bonita, torna a limpeza muito mais simples e rápida. O grande destaque é o queimador tripla-chama, que garante maior potência e rapidez no cozimento de grandes porções. O forno de 96,5 litros é um dos maiores da categoria e conta com prateleiras deslizantes e vidro interno removível, facilitando o uso e a limpeza. Os botões removíveis e o acendimento automático são características que agregam praticidade e segurança ao dia a dia. É um investimento que vale a pena para quem busca um fogão completo, potente e com design diferenciado.`,
    technicalSpecs: {
      'Tipo': 'Fogão de Piso',
      'Queimadores': '5 (1 Tripla-Chama, 2 Rápidos, 2 Semirrápidos)',
      'Acendimento': 'Automático',
      'Mesa': 'Vidro Temperado Preto',
      'Forno': '96.5 Litros',
      'Luz Interna': 'Sim',
      'Cor': 'Inox',
      'Eficiência Energética': 'Classe A',
      'Voltagem': 'Bivolt',
      'Altura': '95.5 cm',
      'Largura': '76.2 cm',
      'Profundidade': '68.7 cm',
      'Peso': '45 kg'
    },
    scores: {
      'Desempenho dos Queimadores': 9.5,
      'Capacidade do Forno': 9.7,
      'Design e Acabamento': 9.2,
      'Custo-benefício': 8.8,
    },
    publishedAt: '2024-08-05T10:00:00Z',
    offers: [
      { id: '1', store: 'Magazine Luiza', storeLogoUrl: '/images/stores/magalu.svg', price: 2199.00, offerUrl: '#' },
      { id: '2', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 2249.00, offerUrl: '#' },
      { id: '3', store: 'Ponto', storeLogoUrl: '/images/stores/ponto.svg', price: 2219.00, offerUrl: '#' },
    ],
  },
  {
    id: '13',
    slug: 'micro-ondas-consul-32l-inox-espelhado',
    title: 'Micro-ondas Consul 32L Inox Espelhado com Menu Fácil',
    category: 'micro-ondas',
    rating: 4.7,
    image: findImage('microwave-2'),
    summary: 'Aliado perfeito para o dia a dia, com design moderno e funções que simplificam a rotina.',
    content: `O Micro-ondas Consul 32L combina um design sofisticado em inox espelhado com funcionalidades pensadas para a praticidade. Com 32 litros de capacidade, é ideal para famílias e para quem utiliza recipientes maiores. O Menu Fácil oferece acesso rápido a 6 receitas pré-programadas, ajustando potência e tempo automaticamente. A função "Descongelar por Peso" garante que carnes, frangos e feijão sejam descongelados de maneira uniforme. Um diferencial é o "Pote na Medida Certa", um acessório que acompanha o produto, perfeito para preparar receitas como arroz e brigadeirão diretamente no micro-ondas. O painel numérico facilita o ajuste preciso do tempo.`,
    technicalSpecs: {
      'Capacidade': '32 Litros',
      'Acabamento': 'Porta Espelhada em Inox',
      'Voltagem': '110V ou 220V',
      'Funções': '6 Receitas Pré-programadas',
      'Acessórios': 'Pote de Silicone Culinário',
      'Eficiência Energética': 'Classe A',
      'Trava de Segurança': 'Sim',
      'Largura': '53,9 cm',
      'Altura': '30,1 cm',
      'Profundidade': '42,5 cm',
      'Peso': '16 kg'
    },
    scores: {
      'Capacidade': 9.5,
      'Facilidade de Uso': 9.2,
      'Design': 9.0,
      'Custo-benefício': 8.8,
    },
    publishedAt: '2024-08-06T14:00:00Z',
    offers: [
      { id: '1', store: 'Magazine Luiza', storeLogoUrl: '/images/stores/magalu.svg', price: 829.00, offerUrl: '#' },
      { id: '2', store: 'Ponto', storeLogoUrl: '/images/stores/ponto.svg', price: 849.00, offerUrl: '#' },
    ],
  },
  {
    id: '14',
    slug: 'maquina-de-lavar-brastemp-12kg-bwk12ab',
    title: 'Máquina de Lavar Brastemp 12Kg BWK12AB',
    category: 'maquina-de-lavar',
    rating: 4.8,
    image: findImage('washing-machine-2'),
    summary: 'Potência, eficiência e design moderno para o dia a dia.',
    content: `A Brastemp 12Kg BWK12AB é uma das máquinas mais completas da categoria. Com diversos ciclos automáticos, oferece lavagem eficiente mesmo em roupas muito sujas, sem desperdiçar água. O painel digital é simples e intuitivo, com a função “Turbo Performance” que acelera a lavagem quando há urgência. O cesto de inox garante durabilidade, e o sistema “Enxágue Antialérgico” é ideal para quem tem pele sensível. Um modelo que equilibra bem capacidade, tecnologia e economia.`,
    technicalSpecs: {
      'Capacidade': '12 Kg',
      'Tipo': 'Automática',
      'Material do Cesto': 'Inox',
      'Voltagem': '110V ou 220V',
      'Eficiência Energética': 'Classe A',
      'Programas de Lavagem': '12',
      'Função Turbo': 'Sim',
      'Níveis de Água': '4',
      'Reutilização de Água': 'Sim',
      'Garantia': '12 meses',
      'Altura': '106 cm',
      'Largura': '63 cm',
      'Profundidade': '71 cm',
      'Peso': '38 kg'
    },
    scores: {
      'Custo-benefício': 9.0,
      'Desempenho': 9.5,
      'Capacidade': 9.5,
      'Economia': 9.0
    },
    offers: [
      { id: '1', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 2499.00, offerUrl: '#' },
      { id: '2', store: 'Magazine Luiza', storeLogoUrl: '/images/stores/magalu.svg', price: 2429.00, offerUrl: '#' },
      { id: '3', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 2399.00, offerUrl: '#' }
    ],
    publishedAt: '2024-08-08T10:00:00Z'
  },
  {
    id: '15',
    slug: 'liquidificador-philips-walita-problend-6-1000w',
    title: 'Liquidificador Philips Walita Problend 6 1000W',
    category: 'liquidificador',
    rating: 4.8,
    image: findImage('blender-2'),
    summary: 'Potência e durabilidade para preparar qualquer receita.',
    content: `O Liquidificador Philips Walita Problend 6 é conhecido pela potência de 1000W e lâminas de aço inoxidável com tecnologia Problend 6. Ideal para triturar alimentos duros, fazer vitaminas e massas leves com facilidade. O copo de 2 litros é resistente e o design moderno combina bem com qualquer cozinha. O sistema de travamento garante segurança, e o botão de velocidade variável permite total controle do preparo.`,
    technicalSpecs: {
      'Potência': '1000W',
      'Capacidade': '2 Litros',
      'Velocidades': '5 + Pulsar',
      'Material do Copo': 'SAN (Resistente a impacto)',
      'Lâminas': 'Aço inox Problend 6',
      'Voltagem': '110V ou 220V',
      'Consumo': '1,2 kWh',
      'Cor': 'Preta/Inox',
      'Garantia': '24 meses'
    },
    scores: {
      'Custo-benefício': 9.0,
      'Potência': 9.5,
      'Capacidade': 9.0,
      'Durabilidade': 9.5
    },
    offers: [
      { id: '1', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 369.00, offerUrl: '#' },
      { id: '2', store: 'Magazine Luiza', storeLogoUrl: '/images/stores/magalu.svg', price: 379.00, offerUrl: '#' },
      { id: '3', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 365.00, offerUrl: '#' }
    ],
    publishedAt: '2024-08-10T11:00:00Z'
  },
  {
    id: '16',
    slug: 'televisao-lg-50-4k-uhd-thinq-ai',
    title: 'Televisão LG 50” 4K UHD ThinQ AI',
    category: 'televisao',
    rating: 4.9,
    image: findImage('television-2'),
    summary: 'Imagem incrível e conectividade inteligente.',
    content: `A Smart TV LG 50” 4K UHD ThinQ AI é uma das mais completas da categoria. Com painel IPS 4K, oferece imagens nítidas e cores vibrantes em qualquer ângulo. O sistema webOS é fluido e fácil de usar, com acesso rápido a apps como Netflix, YouTube e Prime Video. O controle Smart Magic permite comandos por voz e integração com Alexa e Google Assistente. Ideal para quem busca qualidade de imagem e funções inteligentes.`,
    technicalSpecs: {
      'Tamanho da Tela': '50 polegadas',
      'Resolução': '4K UHD (3840x2160)',
      'Painel': 'LED IPS',
      'HDR': 'Sim (HDR10, HLG)',
      'Sistema Operacional': 'webOS',
      'Wi-Fi / Bluetooth': 'Sim',
      'Entradas HDMI': '3',
      'Entradas USB': '2',
      'Assistente de Voz': 'Alexa / Google Assistente',
      'Consumo': '85W',
      'Garantia': '12 meses'
    },
    scores: {
      'Custo-benefício': 9.0,
      'Qualidade de Imagem': 9.8,
      'Sistema Inteligente': 9.5,
      'Conectividade': 9.5
    },
    offers: [
      { id: '1', store: 'Amazon', storeLogoUrl: '/images/stores/amazon.svg', price: 2599.00, offerUrl: '#' },
      { id: '2', store: 'Casas Bahia', storeLogoUrl: '/images/stores/casas-bahia.svg', price: 2649.00, offerUrl: '#' },
      { id: '3', store: 'Ponto', storeLogoUrl: '/images/stores/ponto.svg', price: 2619.00, offerUrl: '#' }
    ],
    publishedAt: '2024-08-12T11:00:00Z'
  }
];

    
